[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"'
'''
desc = "Go to the root of current Git repo"

[[manager.prepend_keymap]]
on   = "e"
run  = "plugin hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on   = "E"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on  = "k"
run = "plugin arrow --args=-1"

[[manager.prepend_keymap]]
on  = "j"
run = "plugin arrow --args=1"

[[manager.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[manager.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"
