[manager]
# ratio = [1, 3, 3]
sort_by = "extension"
sort_sensitive = true
sort_dir_first = true
linemode = "size_and_mtime"
show_symlink = false
show_hidden = true

[preview]
wrap = "yes"
tab_size = 2
image_delay = 50

[input]
cursor_blink = false

[which]
sort_by = "key"
sort_sensitive = true
sort_translit = true
